import {
  Circle,
  Flame,
  Droplet,
  Leaf,
  Zap,
  Snowflake,
  HandFist,
  Skull,
  Mountain,
  Wind,
  Brain,
  Bug,
  Gem,
  Ghost,
  Swords,
  Moon,
  Cog,
  Sparkles,
  type LucideIcon,
} from "lucide-react";
export const pokemonTypeStyleDictionary: Record<
  string,
  { ja: string; color: string; icon: LucideIcon }
> = {
  normal: { ja: "ノーマル", color: "#A8A878", icon: Circle },
  fire: { ja: "ほのお", color: "#F08030", icon: Flame },
  water: { ja: "みず", color: "#6890F0", icon: Droplet },
  grass: { ja: "くさ", color: "#78C850", icon: Leaf },
  electric: { ja: "でんき", color: "#F8D030", icon: Zap },
  ice: { ja: "こおり", color: "#98D8D8", icon: Snowflake },
  fighting: { ja: "かくとう", color: "#C03028", icon: HandFist },
  poison: { ja: "どく", color: "#A040A0", icon: Skull },
  ground: { ja: "じめん", color: "#E0C068", icon: Mountain },
  flying: { ja: "ひこう", color: "#A890F0", icon: Wind },
  psychic: { ja: "エスパー", color: "#F85888", icon: Brain },
  bug: { ja: "むし", color: "#A8B820", icon: Bug },
  rock: { ja: "いわ", color: "#B8A038", icon: Gem },
  ghost: { ja: "ゴースト", color: "#705898", icon: Ghost },
  dragon: { ja: "ドラゴン", color: "#7038F8", icon: Swords },
  dark: { ja: "あく", color: "#705848", icon: Moon },
  steel: { ja: "はがね", color: "#B8B8D0", icon: Cog },
  fairy: { ja: "フェアリー", color: "#EE99AC", icon: Sparkles },
};
